/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerId = IDL.Nat;
export const JamaId = IDL.Nat;
export const UdharId = IDL.Nat;
export const CustomerStatus = IDL.Variant({
  'active' : IDL.Null,
  'overdue' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CustomerView = IDL.Record({
  'id' : CustomerId,
  'status' : CustomerStatus,
  'blocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'creditLimit' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'outstandingBalance' : IDL.Int,
});
export const PaymentType = IDL.Variant({
  'cash' : IDL.Null,
  'deposit' : IDL.Null,
  'online' : IDL.Null,
});
export const JamaView = IDL.Record({
  'id' : JamaId,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'paymentType' : PaymentType,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const RepaymentMode = IDL.Variant({
  'endOfTerm' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
  'halfYearly' : IDL.Null,
  'daily' : IDL.Null,
});
export const RepaymentType = IDL.Variant({
  'interestLoan' : IDL.Null,
  'simple' : IDL.Null,
  'fixedDaily' : IDL.Null,
});
export const UdharView = IDL.Record({
  'id' : UdharId,
  'loanDurationMonths' : IDL.Opt(IDL.Nat),
  'dailyInstallment' : IDL.Opt(IDL.Float64),
  'createdAt' : Timestamp,
  'dueDate' : IDL.Opt(Timestamp),
  'totalInterest' : IDL.Opt(IDL.Float64),
  'description' : IDL.Text,
  'totalDays' : IDL.Opt(IDL.Nat),
  'quarterlyInstallment' : IDL.Opt(IDL.Float64),
  'dailyAmount' : IDL.Opt(IDL.Float64),
  'interestRate' : IDL.Opt(IDL.Float64),
  'totalPayable' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Text,
  'halfYearlyInstallment' : IDL.Opt(IDL.Float64),
  'emiAmount' : IDL.Opt(IDL.Float64),
  'repaymentMode' : IDL.Opt(RepaymentMode),
  'repaymentType' : IDL.Opt(RepaymentType),
  'customerId' : CustomerId,
  'monthlyInstallment' : IDL.Opt(IDL.Float64),
  'amount' : IDL.Nat,
  'profitAmount' : IDL.Opt(IDL.Float64),
  'totalToCollect' : IDL.Opt(IDL.Float64),
});
export const AdminStats = IDL.Record({
  'totalUdharAmount' : IDL.Float64,
  'totalJama' : IDL.Nat,
  'totalJamaAmount' : IDL.Float64,
  'blockedCount' : IDL.Nat,
  'totalUdhar' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const UpdateCustomerArgs = IDL.Record({
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'creditLimit' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
});
export const CreateCustomerArgs = IDL.Record({
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'creditLimit' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
});
export const CreateJamaArgs = IDL.Record({
  'notes' : IDL.Text,
  'paymentType' : PaymentType,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const CreateUdharArgs = IDL.Record({
  'loanDurationMonths' : IDL.Opt(IDL.Nat),
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'totalDays' : IDL.Opt(IDL.Nat),
  'dailyAmount' : IDL.Opt(IDL.Float64),
  'interestRate' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Text,
  'repaymentMode' : IDL.Opt(RepaymentMode),
  'repaymentType' : IDL.Opt(RepaymentType),
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const TopCustomer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'outstandingBalance' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'todayCollection' : IDL.Nat,
  'top5CustomersByBalance' : IDL.Vec(TopCustomer),
  'totalJama' : IDL.Nat,
  'totalUdhar' : IDL.Nat,
  'pendingBalance' : IDL.Int,
  'overdueCustomerCount' : IDL.Nat,
});
export const Result_5 = IDL.Variant({ 'ok' : CustomerView, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
export const PaymentRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const CustomerPaymentRequestView = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentRequestStatus,
  'customerPrincipal' : IDL.Principal,
  'createdAt' : Timestamp,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'paymentType' : PaymentType,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
  'shopOwnerPrincipal' : IDL.Principal,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(CustomerPaymentRequestView),
  'err' : IDL.Text,
});
export const TransactionKind = IDL.Variant({
  'jama' : IDL.Null,
  'udhar' : IDL.Null,
});
export const TransactionEntry = IDL.Record({
  'id' : IDL.Nat,
  'kind' : TransactionKind,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(TransactionEntry),
  'err' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'timezone' : IDL.Text,
  'country' : IDL.Text,
  'businessName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'language' : IDL.Text,
  'dateFormat' : IDL.Text,
  'currency' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Result = IDL.Variant({
  'ok' : CustomerPaymentRequestView,
  'err' : IDL.Text,
});
export const UpdateJamaArgs = IDL.Record({
  'notes' : IDL.Text,
  'paymentType' : PaymentType,
  'amount' : IDL.Nat,
});
export const UpdateUdharArgs = IDL.Record({
  'loanDurationMonths' : IDL.Opt(IDL.Nat),
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'totalDays' : IDL.Opt(IDL.Nat),
  'dailyAmount' : IDL.Opt(IDL.Float64),
  'interestRate' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Text,
  'repaymentMode' : IDL.Opt(RepaymentMode),
  'repaymentType' : IDL.Opt(RepaymentType),
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminBlockCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'adminDeleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'adminDeleteJama' : IDL.Func([JamaId], [IDL.Bool], []),
  'adminDeleteUdhar' : IDL.Func([UdharId], [IDL.Bool], []),
  'adminGetAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'adminGetAllCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
  'adminGetAllJama' : IDL.Func([], [IDL.Vec(JamaView)], ['query']),
  'adminGetAllUdhar' : IDL.Func([], [IDL.Vec(UdharView)], ['query']),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'adminUnblockCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'adminUpdateCustomer' : IDL.Func(
      [CustomerId, UpdateCustomerArgs],
      [IDL.Opt(CustomerView)],
      [],
    ),
  'createCustomer' : IDL.Func([CreateCustomerArgs], [CustomerView], []),
  'createJama' : IDL.Func([CreateJamaArgs], [JamaView], []),
  'createUdhar' : IDL.Func([CreateUdharArgs], [UdharView], []),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteJama' : IDL.Func([JamaId], [IDL.Bool], []),
  'deleteUdhar' : IDL.Func([UdharId], [IDL.Bool], []),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(CustomerView)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDueTodayReminders' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
  'getJamaByCustomer' : IDL.Func([CustomerId], [IDL.Vec(JamaView)], ['query']),
  'getMyCustomerProfile' : IDL.Func([], [Result_5], ['query']),
  'getMyOutstandingBalance' : IDL.Func([], [Result_4], ['query']),
  'getMyPaymentRequests' : IDL.Func([], [Result_3], ['query']),
  'getMyPendingPaymentRequests' : IDL.Func([], [Result_3], ['query']),
  'getMyTransactionHistory' : IDL.Func([], [Result_2], ['query']),
  'getTransactionHistory' : IDL.Func(
      [CustomerId],
      [IDL.Vec(TransactionEntry)],
      ['query'],
    ),
  'getUdharByCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(UdharView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [UserProfile], []),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'linkMyAccount' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
  'ownerApprovePaymentRequest' : IDL.Func([IDL.Nat], [Result_1], []),
  'ownerGetAllPaymentRequests' : IDL.Func(
      [],
      [IDL.Vec(CustomerPaymentRequestView)],
      ['query'],
    ),
  'ownerGetPendingPaymentRequests' : IDL.Func(
      [],
      [IDL.Vec(CustomerPaymentRequestView)],
      ['query'],
    ),
  'ownerRejectPaymentRequest' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'submitPaymentRequest' : IDL.Func(
      [IDL.Nat, PaymentType, IDL.Text],
      [Result],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [CustomerId, UpdateCustomerArgs],
      [IDL.Opt(CustomerView)],
      [],
    ),
  'updateJama' : IDL.Func([JamaId, UpdateJamaArgs], [IDL.Opt(JamaView)], []),
  'updateUdhar' : IDL.Func(
      [UdharId, UpdateUdharArgs],
      [IDL.Opt(UdharView)],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerId = IDL.Nat;
  const JamaId = IDL.Nat;
  const UdharId = IDL.Nat;
  const CustomerStatus = IDL.Variant({
    'active' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CustomerView = IDL.Record({
    'id' : CustomerId,
    'status' : CustomerStatus,
    'blocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'creditLimit' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'outstandingBalance' : IDL.Int,
  });
  const PaymentType = IDL.Variant({
    'cash' : IDL.Null,
    'deposit' : IDL.Null,
    'online' : IDL.Null,
  });
  const JamaView = IDL.Record({
    'id' : JamaId,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'paymentType' : PaymentType,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const RepaymentMode = IDL.Variant({
    'endOfTerm' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
    'halfYearly' : IDL.Null,
    'daily' : IDL.Null,
  });
  const RepaymentType = IDL.Variant({
    'interestLoan' : IDL.Null,
    'simple' : IDL.Null,
    'fixedDaily' : IDL.Null,
  });
  const UdharView = IDL.Record({
    'id' : UdharId,
    'loanDurationMonths' : IDL.Opt(IDL.Nat),
    'dailyInstallment' : IDL.Opt(IDL.Float64),
    'createdAt' : Timestamp,
    'dueDate' : IDL.Opt(Timestamp),
    'totalInterest' : IDL.Opt(IDL.Float64),
    'description' : IDL.Text,
    'totalDays' : IDL.Opt(IDL.Nat),
    'quarterlyInstallment' : IDL.Opt(IDL.Float64),
    'dailyAmount' : IDL.Opt(IDL.Float64),
    'interestRate' : IDL.Opt(IDL.Float64),
    'totalPayable' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Text,
    'halfYearlyInstallment' : IDL.Opt(IDL.Float64),
    'emiAmount' : IDL.Opt(IDL.Float64),
    'repaymentMode' : IDL.Opt(RepaymentMode),
    'repaymentType' : IDL.Opt(RepaymentType),
    'customerId' : CustomerId,
    'monthlyInstallment' : IDL.Opt(IDL.Float64),
    'amount' : IDL.Nat,
    'profitAmount' : IDL.Opt(IDL.Float64),
    'totalToCollect' : IDL.Opt(IDL.Float64),
  });
  const AdminStats = IDL.Record({
    'totalUdharAmount' : IDL.Float64,
    'totalJama' : IDL.Nat,
    'totalJamaAmount' : IDL.Float64,
    'blockedCount' : IDL.Nat,
    'totalUdhar' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const UpdateCustomerArgs = IDL.Record({
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'creditLimit' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
  });
  const CreateCustomerArgs = IDL.Record({
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'creditLimit' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
  });
  const CreateJamaArgs = IDL.Record({
    'notes' : IDL.Text,
    'paymentType' : PaymentType,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const CreateUdharArgs = IDL.Record({
    'loanDurationMonths' : IDL.Opt(IDL.Nat),
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'totalDays' : IDL.Opt(IDL.Nat),
    'dailyAmount' : IDL.Opt(IDL.Float64),
    'interestRate' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Text,
    'repaymentMode' : IDL.Opt(RepaymentMode),
    'repaymentType' : IDL.Opt(RepaymentType),
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const TopCustomer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'outstandingBalance' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'todayCollection' : IDL.Nat,
    'top5CustomersByBalance' : IDL.Vec(TopCustomer),
    'totalJama' : IDL.Nat,
    'totalUdhar' : IDL.Nat,
    'pendingBalance' : IDL.Int,
    'overdueCustomerCount' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({ 'ok' : CustomerView, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
  const PaymentRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const CustomerPaymentRequestView = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentRequestStatus,
    'customerPrincipal' : IDL.Principal,
    'createdAt' : Timestamp,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'paymentType' : PaymentType,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
    'shopOwnerPrincipal' : IDL.Principal,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Vec(CustomerPaymentRequestView),
    'err' : IDL.Text,
  });
  const TransactionKind = IDL.Variant({
    'jama' : IDL.Null,
    'udhar' : IDL.Null,
  });
  const TransactionEntry = IDL.Record({
    'id' : IDL.Nat,
    'kind' : TransactionKind,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(TransactionEntry),
    'err' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'timezone' : IDL.Text,
    'country' : IDL.Text,
    'businessName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'language' : IDL.Text,
    'dateFormat' : IDL.Text,
    'currency' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Result = IDL.Variant({
    'ok' : CustomerPaymentRequestView,
    'err' : IDL.Text,
  });
  const UpdateJamaArgs = IDL.Record({
    'notes' : IDL.Text,
    'paymentType' : PaymentType,
    'amount' : IDL.Nat,
  });
  const UpdateUdharArgs = IDL.Record({
    'loanDurationMonths' : IDL.Opt(IDL.Nat),
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'totalDays' : IDL.Opt(IDL.Nat),
    'dailyAmount' : IDL.Opt(IDL.Float64),
    'interestRate' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Text,
    'repaymentMode' : IDL.Opt(RepaymentMode),
    'repaymentType' : IDL.Opt(RepaymentType),
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminBlockCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'adminDeleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'adminDeleteJama' : IDL.Func([JamaId], [IDL.Bool], []),
    'adminDeleteUdhar' : IDL.Func([UdharId], [IDL.Bool], []),
    'adminGetAdminPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'adminGetAllCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
    'adminGetAllJama' : IDL.Func([], [IDL.Vec(JamaView)], ['query']),
    'adminGetAllUdhar' : IDL.Func([], [IDL.Vec(UdharView)], ['query']),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'adminUnblockCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'adminUpdateCustomer' : IDL.Func(
        [CustomerId, UpdateCustomerArgs],
        [IDL.Opt(CustomerView)],
        [],
      ),
    'createCustomer' : IDL.Func([CreateCustomerArgs], [CustomerView], []),
    'createJama' : IDL.Func([CreateJamaArgs], [JamaView], []),
    'createUdhar' : IDL.Func([CreateUdharArgs], [UdharView], []),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteJama' : IDL.Func([JamaId], [IDL.Bool], []),
    'deleteUdhar' : IDL.Func([UdharId], [IDL.Bool], []),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(CustomerView)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDueTodayReminders' : IDL.Func([], [IDL.Vec(CustomerView)], ['query']),
    'getJamaByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(JamaView)],
        ['query'],
      ),
    'getMyCustomerProfile' : IDL.Func([], [Result_5], ['query']),
    'getMyOutstandingBalance' : IDL.Func([], [Result_4], ['query']),
    'getMyPaymentRequests' : IDL.Func([], [Result_3], ['query']),
    'getMyPendingPaymentRequests' : IDL.Func([], [Result_3], ['query']),
    'getMyTransactionHistory' : IDL.Func([], [Result_2], ['query']),
    'getTransactionHistory' : IDL.Func(
        [CustomerId],
        [IDL.Vec(TransactionEntry)],
        ['query'],
      ),
    'getUdharByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(UdharView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [UserProfile], []),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'linkMyAccount' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
    'ownerApprovePaymentRequest' : IDL.Func([IDL.Nat], [Result_1], []),
    'ownerGetAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(CustomerPaymentRequestView)],
        ['query'],
      ),
    'ownerGetPendingPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(CustomerPaymentRequestView)],
        ['query'],
      ),
    'ownerRejectPaymentRequest' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'submitPaymentRequest' : IDL.Func(
        [IDL.Nat, PaymentType, IDL.Text],
        [Result],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [CustomerId, UpdateCustomerArgs],
        [IDL.Opt(CustomerView)],
        [],
      ),
    'updateJama' : IDL.Func([JamaId, UpdateJamaArgs], [IDL.Opt(JamaView)], []),
    'updateUdhar' : IDL.Func(
        [UdharId, UpdateUdharArgs],
        [IDL.Opt(UdharView)],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };