/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalUdharAmount' : number,
  'totalJama' : bigint,
  'totalJamaAmount' : number,
  'blockedCount' : bigint,
  'totalUdhar' : bigint,
  'totalCustomers' : bigint,
}
export interface CreateCustomerArgs {
  'name' : string,
  'mobileNumber' : string,
  'email' : [] | [string],
  'creditLimit' : bigint,
  'address' : string,
  'notes' : string,
}
export interface CreateJamaArgs {
  'notes' : string,
  'paymentType' : PaymentType,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export interface CreateUdharArgs {
  'loanDurationMonths' : [] | [bigint],
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'totalDays' : [] | [bigint],
  'dailyAmount' : [] | [number],
  'interestRate' : [] | [number],
  'notes' : string,
  'repaymentMode' : [] | [RepaymentMode],
  'repaymentType' : [] | [RepaymentType],
  'customerId' : CustomerId,
  'amount' : bigint,
}
export type CustomerId = bigint;
export interface CustomerPaymentRequestView {
  'id' : bigint,
  'status' : PaymentRequestStatus,
  'customerPrincipal' : Principal,
  'createdAt' : Timestamp,
  'rejectionReason' : [] | [string],
  'notes' : string,
  'paymentType' : PaymentType,
  'customerId' : CustomerId,
  'amount' : bigint,
  'shopOwnerPrincipal' : Principal,
  'resolvedAt' : [] | [Timestamp],
}
export type CustomerStatus = { 'active' : null } |
  { 'overdue' : null };
export interface CustomerView {
  'id' : CustomerId,
  'status' : CustomerStatus,
  'blocked' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'mobileNumber' : string,
  'email' : [] | [string],
  'creditLimit' : bigint,
  'address' : string,
  'notes' : string,
  'outstandingBalance' : bigint,
}
export interface DashboardStats {
  'todayCollection' : bigint,
  'top5CustomersByBalance' : Array<TopCustomer>,
  'totalJama' : bigint,
  'totalUdhar' : bigint,
  'pendingBalance' : bigint,
  'overdueCustomerCount' : bigint,
}
export type JamaId = bigint;
export interface JamaView {
  'id' : JamaId,
  'createdAt' : Timestamp,
  'notes' : string,
  'paymentType' : PaymentType,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export type PaymentRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type PaymentType = { 'cash' : null } |
  { 'deposit' : null } |
  { 'online' : null };
export type RepaymentMode = { 'endOfTerm' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'halfYearly' : null } |
  { 'daily' : null };
export type RepaymentType = { 'interestLoan' : null } |
  { 'simple' : null } |
  { 'fixedDaily' : null };
export type Result = { 'ok' : CustomerPaymentRequestView } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type Result_2 = { 'ok' : Array<TransactionEntry> } |
  { 'err' : string };
export type Result_3 = { 'ok' : Array<CustomerPaymentRequestView> } |
  { 'err' : string };
export type Result_4 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_5 = { 'ok' : CustomerView } |
  { 'err' : string };
export type Timestamp = bigint;
export interface TopCustomer {
  'id' : CustomerId,
  'name' : string,
  'outstandingBalance' : bigint,
}
export interface TransactionEntry {
  'id' : bigint,
  'kind' : TransactionKind,
  'createdAt' : Timestamp,
  'description' : string,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export type TransactionKind = { 'jama' : null } |
  { 'udhar' : null };
export type UdharId = bigint;
export interface UdharView {
  'id' : UdharId,
  'loanDurationMonths' : [] | [bigint],
  'dailyInstallment' : [] | [number],
  'createdAt' : Timestamp,
  'dueDate' : [] | [Timestamp],
  'totalInterest' : [] | [number],
  'description' : string,
  'totalDays' : [] | [bigint],
  'quarterlyInstallment' : [] | [number],
  'dailyAmount' : [] | [number],
  'interestRate' : [] | [number],
  'totalPayable' : [] | [number],
  'notes' : string,
  'halfYearlyInstallment' : [] | [number],
  'emiAmount' : [] | [number],
  'repaymentMode' : [] | [RepaymentMode],
  'repaymentType' : [] | [RepaymentType],
  'customerId' : CustomerId,
  'monthlyInstallment' : [] | [number],
  'amount' : bigint,
  'profitAmount' : [] | [number],
  'totalToCollect' : [] | [number],
}
export interface UpdateCustomerArgs {
  'name' : string,
  'mobileNumber' : string,
  'email' : [] | [string],
  'creditLimit' : bigint,
  'address' : string,
  'notes' : string,
}
export interface UpdateJamaArgs {
  'notes' : string,
  'paymentType' : PaymentType,
  'amount' : bigint,
}
export interface UpdateUdharArgs {
  'loanDurationMonths' : [] | [bigint],
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'totalDays' : [] | [bigint],
  'dailyAmount' : [] | [number],
  'interestRate' : [] | [number],
  'notes' : string,
  'repaymentMode' : [] | [RepaymentMode],
  'repaymentType' : [] | [RepaymentType],
  'amount' : bigint,
}
export interface UserProfile {
  'timezone' : string,
  'country' : string,
  'businessName' : string,
  'mobileNumber' : string,
  'language' : string,
  'dateFormat' : string,
  'currency' : string,
}
export interface _SERVICE {
  'adminBlockCustomer' : ActorMethod<[CustomerId], boolean>,
  'adminDeleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'adminDeleteJama' : ActorMethod<[JamaId], boolean>,
  'adminDeleteUdhar' : ActorMethod<[UdharId], boolean>,
  'adminGetAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'adminGetAllCustomers' : ActorMethod<[], Array<CustomerView>>,
  'adminGetAllJama' : ActorMethod<[], Array<JamaView>>,
  'adminGetAllUdhar' : ActorMethod<[], Array<UdharView>>,
  'adminGetStats' : ActorMethod<[], AdminStats>,
  'adminUnblockCustomer' : ActorMethod<[CustomerId], boolean>,
  'adminUpdateCustomer' : ActorMethod<
    [CustomerId, UpdateCustomerArgs],
    [] | [CustomerView]
  >,
  'createCustomer' : ActorMethod<[CreateCustomerArgs], CustomerView>,
  'createJama' : ActorMethod<[CreateJamaArgs], JamaView>,
  'createUdhar' : ActorMethod<[CreateUdharArgs], UdharView>,
  'deleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'deleteJama' : ActorMethod<[JamaId], boolean>,
  'deleteUdhar' : ActorMethod<[UdharId], boolean>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [CustomerView]>,
  'getCustomers' : ActorMethod<[], Array<CustomerView>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDueTodayReminders' : ActorMethod<[], Array<CustomerView>>,
  'getJamaByCustomer' : ActorMethod<[CustomerId], Array<JamaView>>,
  'getMyCustomerProfile' : ActorMethod<[], Result_5>,
  'getMyOutstandingBalance' : ActorMethod<[], Result_4>,
  'getMyPaymentRequests' : ActorMethod<[], Result_3>,
  'getMyPendingPaymentRequests' : ActorMethod<[], Result_3>,
  'getMyTransactionHistory' : ActorMethod<[], Result_2>,
  'getTransactionHistory' : ActorMethod<[CustomerId], Array<TransactionEntry>>,
  'getUdharByCustomer' : ActorMethod<[CustomerId], Array<UdharView>>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'linkMyAccount' : ActorMethod<[bigint, string], Result_1>,
  'ownerApprovePaymentRequest' : ActorMethod<[bigint], Result_1>,
  'ownerGetAllPaymentRequests' : ActorMethod<
    [],
    Array<CustomerPaymentRequestView>
  >,
  'ownerGetPendingPaymentRequests' : ActorMethod<
    [],
    Array<CustomerPaymentRequestView>
  >,
  'ownerRejectPaymentRequest' : ActorMethod<[bigint, string], Result_1>,
  'setAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'submitPaymentRequest' : ActorMethod<[bigint, PaymentType, string], Result>,
  'updateCustomer' : ActorMethod<
    [CustomerId, UpdateCustomerArgs],
    [] | [CustomerView]
  >,
  'updateJama' : ActorMethod<[JamaId, UpdateJamaArgs], [] | [JamaView]>,
  'updateUdhar' : ActorMethod<[UdharId, UpdateUdharArgs], [] | [UdharView]>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];