/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Array<TransactionEntry>;
} | {
    __kind__: "err";
    err: string;
};
export interface UdharView {
    id: UdharId;
    loanDurationMonths?: bigint;
    dailyInstallment?: number;
    createdAt: Timestamp;
    dueDate?: Timestamp;
    totalInterest?: number;
    description: string;
    totalDays?: bigint;
    quarterlyInstallment?: number;
    dailyAmount?: number;
    interestRate?: number;
    totalPayable?: number;
    notes: string;
    halfYearlyInstallment?: number;
    emiAmount?: number;
    repaymentMode?: RepaymentMode;
    repaymentType?: RepaymentType;
    customerId: CustomerId;
    monthlyInstallment?: number;
    amount: bigint;
    profitAmount?: number;
    totalToCollect?: number;
}
export type Result_5 = {
    __kind__: "ok";
    ok: CustomerView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface CreateJamaArgs {
    notes: string;
    paymentType: PaymentType;
    customerId: CustomerId;
    amount: bigint;
}
export interface CreateCustomerArgs {
    name: string;
    mobileNumber: string;
    email?: string;
    creditLimit: bigint;
    address: string;
    notes: string;
}
export type Result_4 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface JamaView {
    id: JamaId;
    createdAt: Timestamp;
    notes: string;
    paymentType: PaymentType;
    customerId: CustomerId;
    amount: bigint;
}
export interface TopCustomer {
    id: CustomerId;
    name: string;
    outstandingBalance: bigint;
}
export interface UpdateCustomerArgs {
    name: string;
    mobileNumber: string;
    email?: string;
    creditLimit: bigint;
    address: string;
    notes: string;
}
export type UdharId = bigint;
export interface CustomerPaymentRequestView {
    id: bigint;
    status: PaymentRequestStatus;
    customerPrincipal: Principal;
    createdAt: Timestamp;
    rejectionReason?: string;
    notes: string;
    paymentType: PaymentType;
    customerId: CustomerId;
    amount: bigint;
    shopOwnerPrincipal: Principal;
    resolvedAt?: Timestamp;
}
export interface UpdateUdharArgs {
    loanDurationMonths?: bigint;
    dueDate?: Timestamp;
    description: string;
    totalDays?: bigint;
    dailyAmount?: number;
    interestRate?: number;
    notes: string;
    repaymentMode?: RepaymentMode;
    repaymentType?: RepaymentType;
    amount: bigint;
}
export interface UpdateJamaArgs {
    notes: string;
    paymentType: PaymentType;
    amount: bigint;
}
export interface DashboardStats {
    todayCollection: bigint;
    top5CustomersByBalance: Array<TopCustomer>;
    totalJama: bigint;
    totalUdhar: bigint;
    pendingBalance: bigint;
    overdueCustomerCount: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: CustomerPaymentRequestView;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Array<CustomerPaymentRequestView>;
} | {
    __kind__: "err";
    err: string;
};
export interface TransactionEntry {
    id: bigint;
    kind: TransactionKind;
    createdAt: Timestamp;
    description: string;
    customerId: CustomerId;
    amount: bigint;
}
export type CustomerId = bigint;
export interface AdminStats {
    totalUdharAmount: number;
    totalJama: bigint;
    totalJamaAmount: number;
    blockedCount: bigint;
    totalUdhar: bigint;
    totalCustomers: bigint;
}
export interface CustomerView {
    id: CustomerId;
    status: CustomerStatus;
    blocked: boolean;
    name: string;
    createdAt: Timestamp;
    mobileNumber: string;
    email?: string;
    creditLimit: bigint;
    address: string;
    notes: string;
    outstandingBalance: bigint;
}
export interface CreateUdharArgs {
    loanDurationMonths?: bigint;
    dueDate?: Timestamp;
    description: string;
    totalDays?: bigint;
    dailyAmount?: number;
    interestRate?: number;
    notes: string;
    repaymentMode?: RepaymentMode;
    repaymentType?: RepaymentType;
    customerId: CustomerId;
    amount: bigint;
}
export interface UserProfile {
    timezone: string;
    country: string;
    businessName: string;
    mobileNumber: string;
    language: string;
    dateFormat: string;
    currency: string;
}
export type JamaId = bigint;
export enum CustomerStatus {
    active = "active",
    overdue = "overdue"
}
export enum PaymentRequestStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum PaymentType {
    cash = "cash",
    deposit = "deposit",
    online = "online"
}
export enum RepaymentMode {
    endOfTerm = "endOfTerm",
    quarterly = "quarterly",
    monthly = "monthly",
    halfYearly = "halfYearly",
    daily = "daily"
}
export enum RepaymentType {
    interestLoan = "interestLoan",
    simple = "simple",
    fixedDaily = "fixedDaily"
}
export enum TransactionKind {
    jama = "jama",
    udhar = "udhar"
}
export interface backendInterface {
    adminBlockCustomer(id: CustomerId): Promise<boolean>;
    adminDeleteCustomer(id: CustomerId): Promise<boolean>;
    adminDeleteJama(id: JamaId): Promise<boolean>;
    adminDeleteUdhar(id: UdharId): Promise<boolean>;
    adminGetAdminPrincipal(): Promise<Principal | null>;
    adminGetAllCustomers(): Promise<Array<CustomerView>>;
    adminGetAllJama(): Promise<Array<JamaView>>;
    adminGetAllUdhar(): Promise<Array<UdharView>>;
    adminGetStats(): Promise<AdminStats>;
    adminUnblockCustomer(id: CustomerId): Promise<boolean>;
    adminUpdateCustomer(id: CustomerId, args: UpdateCustomerArgs): Promise<CustomerView | null>;
    createCustomer(args: CreateCustomerArgs): Promise<CustomerView>;
    createJama(args: CreateJamaArgs): Promise<JamaView>;
    createUdhar(args: CreateUdharArgs): Promise<UdharView>;
    deleteCustomer(id: CustomerId): Promise<boolean>;
    deleteJama(id: JamaId): Promise<boolean>;
    deleteUdhar(id: UdharId): Promise<boolean>;
    getCustomer(id: CustomerId): Promise<CustomerView | null>;
    getCustomers(): Promise<Array<CustomerView>>;
    getDashboardStats(): Promise<DashboardStats>;
    getDueTodayReminders(): Promise<Array<CustomerView>>;
    getJamaByCustomer(customerId: CustomerId): Promise<Array<JamaView>>;
    getMyCustomerProfile(): Promise<Result_5>;
    getMyOutstandingBalance(): Promise<Result_4>;
    getMyPaymentRequests(): Promise<Result_3>;
    getMyPendingPaymentRequests(): Promise<Result_3>;
    getMyTransactionHistory(): Promise<Result_2>;
    getTransactionHistory(customerId: CustomerId): Promise<Array<TransactionEntry>>;
    getUdharByCustomer(customerId: CustomerId): Promise<Array<UdharView>>;
    getUserProfile(): Promise<UserProfile>;
    isAdmin(p: Principal): Promise<boolean>;
    linkMyAccount(customerId: bigint, mobileNumber: string): Promise<Result_1>;
    ownerApprovePaymentRequest(requestId: bigint): Promise<Result_1>;
    ownerGetAllPaymentRequests(): Promise<Array<CustomerPaymentRequestView>>;
    ownerGetPendingPaymentRequests(): Promise<Array<CustomerPaymentRequestView>>;
    ownerRejectPaymentRequest(requestId: bigint, reason: string): Promise<Result_1>;
    setAdminPrincipal(p: Principal): Promise<void>;
    submitPaymentRequest(amount: bigint, paymentType: PaymentType, notes: string): Promise<Result>;
    updateCustomer(id: CustomerId, args: UpdateCustomerArgs): Promise<CustomerView | null>;
    updateJama(id: JamaId, args: UpdateJamaArgs): Promise<JamaView | null>;
    updateUdhar(id: UdharId, args: UpdateUdharArgs): Promise<UdharView | null>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { CreateCustomerArgs as _CreateCustomerArgs, CreateJamaArgs as _CreateJamaArgs, CreateUdharArgs as _CreateUdharArgs, CustomerId as _CustomerId, CustomerPaymentRequestView as _CustomerPaymentRequestView, CustomerStatus as _CustomerStatus, CustomerView as _CustomerView, JamaId as _JamaId, JamaView as _JamaView, PaymentRequestStatus as _PaymentRequestStatus, PaymentType as _PaymentType, RepaymentMode as _RepaymentMode, RepaymentType as _RepaymentType, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Timestamp as _Timestamp, TransactionEntry as _TransactionEntry, TransactionKind as _TransactionKind, UdharId as _UdharId, UdharView as _UdharView, UpdateCustomerArgs as _UpdateCustomerArgs, UpdateJamaArgs as _UpdateJamaArgs, UpdateUdharArgs as _UpdateUdharArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminBlockCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBlockCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBlockCustomer(arg0);
            return result;
        }
    }
    async adminDeleteCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCustomer(arg0);
            return result;
        }
    }
    async adminDeleteJama(arg0: JamaId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteJama(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteJama(arg0);
            return result;
        }
    }
    async adminDeleteUdhar(arg0: UdharId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUdhar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUdhar(arg0);
            return result;
        }
    }
    async adminGetAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAdminPrincipal();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAdminPrincipal();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllCustomers(): Promise<Array<CustomerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllCustomers();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllCustomers();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllJama(): Promise<Array<JamaView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllJama();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllJama();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUdhar(): Promise<Array<UdharView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUdhar();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUdhar();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return result;
        }
    }
    async adminUnblockCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnblockCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnblockCustomer(arg0);
            return result;
        }
    }
    async adminUpdateCustomer(arg0: CustomerId, arg1: UpdateCustomerArgs): Promise<CustomerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCustomer(arg0, to_candid_UpdateCustomerArgs_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCustomer(arg0, to_candid_UpdateCustomerArgs_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomer(arg0: CreateCustomerArgs): Promise<CustomerView> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_CreateCustomerArgs_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CustomerView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_CreateCustomerArgs_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CustomerView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJama(arg0: CreateJamaArgs): Promise<JamaView> {
        if (this.processError) {
            try {
                const result = await this.actor.createJama(to_candid_CreateJamaArgs_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JamaView_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJama(to_candid_CreateJamaArgs_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JamaView_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUdhar(arg0: CreateUdharArgs): Promise<UdharView> {
        if (this.processError) {
            try {
                const result = await this.actor.createUdhar(to_candid_CreateUdharArgs_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UdharView_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUdhar(to_candid_CreateUdharArgs_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UdharView_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteJama(arg0: JamaId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJama(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJama(arg0);
            return result;
        }
    }
    async deleteUdhar(arg0: UdharId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUdhar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUdhar(arg0);
            return result;
        }
    }
    async getCustomer(arg0: CustomerId): Promise<CustomerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<CustomerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDueTodayReminders(): Promise<Array<CustomerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueTodayReminders();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueTodayReminders();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJamaByCustomer(arg0: CustomerId): Promise<Array<JamaView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJamaByCustomer(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJamaByCustomer(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCustomerProfile(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomerProfile();
                return from_candid_Result_5_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomerProfile();
            return from_candid_Result_5_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOutstandingBalance(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOutstandingBalance();
                return from_candid_Result_4_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOutstandingBalance();
            return from_candid_Result_4_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPaymentRequests(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPaymentRequests();
                return from_candid_Result_3_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPaymentRequests();
            return from_candid_Result_3_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPendingPaymentRequests(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPendingPaymentRequests();
                return from_candid_Result_3_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPendingPaymentRequests();
            return from_candid_Result_3_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactionHistory(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactionHistory();
                return from_candid_Result_2_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactionHistory();
            return from_candid_Result_2_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(arg0: CustomerId): Promise<Array<TransactionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUdharByCustomer(arg0: CustomerId): Promise<Array<UdharView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUdharByCustomer(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUdharByCustomer(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async linkMyAccount(arg0: bigint, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.linkMyAccount(arg0, arg1);
                return from_candid_Result_1_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkMyAccount(arg0, arg1);
            return from_candid_Result_1_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async ownerApprovePaymentRequest(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerApprovePaymentRequest(arg0);
                return from_candid_Result_1_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerApprovePaymentRequest(arg0);
            return from_candid_Result_1_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async ownerGetAllPaymentRequests(): Promise<Array<CustomerPaymentRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerGetAllPaymentRequests();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerGetAllPaymentRequests();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async ownerGetPendingPaymentRequests(): Promise<Array<CustomerPaymentRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerGetPendingPaymentRequests();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerGetPendingPaymentRequests();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async ownerRejectPaymentRequest(arg0: bigint, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerRejectPaymentRequest(arg0, arg1);
                return from_candid_Result_1_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerRejectPaymentRequest(arg0, arg1);
            return from_candid_Result_1_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminPrincipal(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPrincipal(arg0);
            return result;
        }
    }
    async submitPaymentRequest(arg0: bigint, arg1: PaymentType, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentRequest(arg0, to_candid_PaymentType_n31(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentRequest(arg0, to_candid_PaymentType_n31(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: UpdateCustomerArgs): Promise<CustomerView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_UpdateCustomerArgs_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_UpdateCustomerArgs_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJama(arg0: JamaId, arg1: UpdateJamaArgs): Promise<JamaView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJama(arg0, to_candid_UpdateJamaArgs_n61(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJama(arg0, to_candid_UpdateJamaArgs_n61(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUdhar(arg0: UdharId, arg1: UpdateUdharArgs): Promise<UdharView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUdhar(arg0, to_candid_UpdateUdharArgs_n64(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUdhar(arg0, to_candid_UpdateUdharArgs_n64(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_CustomerPaymentRequestView_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerPaymentRequestView): CustomerPaymentRequestView {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerStatus): CustomerStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerView): CustomerView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_JamaView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JamaView): JamaView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRequestStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequestStatus): PaymentRequestStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RepaymentMode_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepaymentMode): RepaymentMode {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RepaymentType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepaymentType): RepaymentType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionEntry_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionEntry): TransactionEntry {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionKind_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionKind): TransactionKind {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UdharView_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UdharView): UdharView {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepaymentMode]): RepaymentMode | null {
    return value.length === 0 ? null : from_candid_RepaymentMode_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepaymentType]): RepaymentType | null {
    return value.length === 0 ? null : from_candid_RepaymentType_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerView]): CustomerView | null {
    return value.length === 0 ? null : from_candid_CustomerView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JamaView]): JamaView | null {
    return value.length === 0 ? null : from_candid_JamaView_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UdharView]): UdharView | null {
    return value.length === 0 ? null : from_candid_UdharView_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JamaId;
    createdAt: _Timestamp;
    notes: string;
    paymentType: _PaymentType;
    customerId: _CustomerId;
    amount: bigint;
}): {
    id: JamaId;
    createdAt: Timestamp;
    notes: string;
    paymentType: PaymentType;
    customerId: CustomerId;
    amount: bigint;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        notes: value.notes,
        paymentType: from_candid_PaymentType_n11(_uploadFile, _downloadFile, value.paymentType),
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UdharId;
    loanDurationMonths: [] | [bigint];
    dailyInstallment: [] | [number];
    createdAt: _Timestamp;
    dueDate: [] | [_Timestamp];
    totalInterest: [] | [number];
    description: string;
    totalDays: [] | [bigint];
    quarterlyInstallment: [] | [number];
    dailyAmount: [] | [number];
    interestRate: [] | [number];
    totalPayable: [] | [number];
    notes: string;
    halfYearlyInstallment: [] | [number];
    emiAmount: [] | [number];
    repaymentMode: [] | [_RepaymentMode];
    repaymentType: [] | [_RepaymentType];
    customerId: _CustomerId;
    monthlyInstallment: [] | [number];
    amount: bigint;
    profitAmount: [] | [number];
    totalToCollect: [] | [number];
}): {
    id: UdharId;
    loanDurationMonths?: bigint;
    dailyInstallment?: number;
    createdAt: Timestamp;
    dueDate?: Timestamp;
    totalInterest?: number;
    description: string;
    totalDays?: bigint;
    quarterlyInstallment?: number;
    dailyAmount?: number;
    interestRate?: number;
    totalPayable?: number;
    notes: string;
    halfYearlyInstallment?: number;
    emiAmount?: number;
    repaymentMode?: RepaymentMode;
    repaymentType?: RepaymentType;
    customerId: CustomerId;
    monthlyInstallment?: number;
    amount: bigint;
    profitAmount?: number;
    totalToCollect?: number;
} {
    return {
        id: value.id,
        loanDurationMonths: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.loanDurationMonths)),
        dailyInstallment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.dailyInstallment)),
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.dueDate)),
        totalInterest: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.totalInterest)),
        description: value.description,
        totalDays: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.totalDays)),
        quarterlyInstallment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.quarterlyInstallment)),
        dailyAmount: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.dailyAmount)),
        interestRate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.interestRate)),
        totalPayable: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.totalPayable)),
        notes: value.notes,
        halfYearlyInstallment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.halfYearlyInstallment)),
        emiAmount: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.emiAmount)),
        repaymentMode: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.repaymentMode)),
        repaymentType: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.repaymentType)),
        customerId: value.customerId,
        monthlyInstallment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.monthlyInstallment)),
        amount: value.amount,
        profitAmount: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.profitAmount)),
        totalToCollect: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.totalToCollect))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    status: _CustomerStatus;
    blocked: boolean;
    name: string;
    createdAt: _Timestamp;
    mobileNumber: string;
    email: [] | [string];
    creditLimit: bigint;
    address: string;
    notes: string;
    outstandingBalance: bigint;
}): {
    id: CustomerId;
    status: CustomerStatus;
    blocked: boolean;
    name: string;
    createdAt: Timestamp;
    mobileNumber: string;
    email?: string;
    creditLimit: bigint;
    address: string;
    notes: string;
    outstandingBalance: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CustomerStatus_n5(_uploadFile, _downloadFile, value.status),
        blocked: value.blocked,
        name: value.name,
        createdAt: value.createdAt,
        mobileNumber: value.mobileNumber,
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email)),
        creditLimit: value.creditLimit,
        address: value.address,
        notes: value.notes,
        outstandingBalance: value.outstandingBalance
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentRequestStatus;
    customerPrincipal: Principal;
    createdAt: _Timestamp;
    rejectionReason: [] | [string];
    notes: string;
    paymentType: _PaymentType;
    customerId: _CustomerId;
    amount: bigint;
    shopOwnerPrincipal: Principal;
    resolvedAt: [] | [_Timestamp];
}): {
    id: bigint;
    status: PaymentRequestStatus;
    customerPrincipal: Principal;
    createdAt: Timestamp;
    rejectionReason?: string;
    notes: string;
    paymentType: PaymentType;
    customerId: CustomerId;
    amount: bigint;
    shopOwnerPrincipal: Principal;
    resolvedAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_PaymentRequestStatus_n48(_uploadFile, _downloadFile, value.status),
        customerPrincipal: value.customerPrincipal,
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rejectionReason)),
        notes: value.notes,
        paymentType: from_candid_PaymentType_n11(_uploadFile, _downloadFile, value.paymentType),
        customerId: value.customerId,
        amount: value.amount,
        shopOwnerPrincipal: value.shopOwnerPrincipal,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _TransactionKind;
    createdAt: _Timestamp;
    description: string;
    customerId: _CustomerId;
    amount: bigint;
}): {
    id: bigint;
    kind: TransactionKind;
    createdAt: Timestamp;
    description: string;
    customerId: CustomerId;
    amount: bigint;
} {
    return {
        id: value.id,
        kind: from_candid_TransactionKind_n55(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        description: value.description,
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    deposit: null;
} | {
    online: null;
}): PaymentType {
    return "cash" in value ? PaymentType.cash : "deposit" in value ? PaymentType.deposit : "online" in value ? PaymentType.online : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endOfTerm: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} | {
    halfYearly: null;
} | {
    daily: null;
}): RepaymentMode {
    return "endOfTerm" in value ? RepaymentMode.endOfTerm : "quarterly" in value ? RepaymentMode.quarterly : "monthly" in value ? RepaymentMode.monthly : "halfYearly" in value ? RepaymentMode.halfYearly : "daily" in value ? RepaymentMode.daily : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interestLoan: null;
} | {
    simple: null;
} | {
    fixedDaily: null;
}): RepaymentType {
    return "interestLoan" in value ? RepaymentType.interestLoan : "simple" in value ? RepaymentType.simple : "fixedDaily" in value ? RepaymentType.fixedDaily : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CustomerView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CustomerView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CustomerView_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_CustomerPaymentRequestView>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<CustomerPaymentRequestView>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n45(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PaymentRequestStatus {
    return "pending" in value ? PaymentRequestStatus.pending : "approved" in value ? PaymentRequestStatus.approved : "rejected" in value ? PaymentRequestStatus.rejected : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_TransactionEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<TransactionEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jama: null;
} | {
    udhar: null;
}): TransactionKind {
    return "jama" in value ? TransactionKind.jama : "udhar" in value ? TransactionKind.udhar : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    overdue: null;
}): CustomerStatus {
    return "active" in value ? CustomerStatus.active : "overdue" in value ? CustomerStatus.overdue : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CustomerPaymentRequestView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CustomerPaymentRequestView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CustomerPaymentRequestView_n46(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UdharView>): Array<UdharView> {
    return value.map((x)=>from_candid_UdharView_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerView>): Array<CustomerView> {
    return value.map((x)=>from_candid_CustomerView_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerPaymentRequestView>): Array<CustomerPaymentRequestView> {
    return value.map((x)=>from_candid_CustomerPaymentRequestView_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionEntry>): Array<TransactionEntry> {
    return value.map((x)=>from_candid_TransactionEntry_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JamaView>): Array<JamaView> {
    return value.map((x)=>from_candid_JamaView_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CreateCustomerArgs_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCustomerArgs): _CreateCustomerArgs {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_CreateJamaArgs_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJamaArgs): _CreateJamaArgs {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_CreateUdharArgs_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateUdharArgs): _CreateUdharArgs {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_RepaymentMode_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepaymentMode): _RepaymentMode {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_RepaymentType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepaymentType): _RepaymentType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCustomerArgs_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCustomerArgs): _UpdateCustomerArgs {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJamaArgs_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJamaArgs): _UpdateJamaArgs {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUdharArgs_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUdharArgs): _UpdateUdharArgs {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    mobileNumber: string;
    email?: string;
    creditLimit: bigint;
    address: string;
    notes: string;
}): {
    name: string;
    mobileNumber: string;
    email: [] | [string];
    creditLimit: bigint;
    address: string;
    notes: string;
} {
    return {
        name: value.name,
        mobileNumber: value.mobileNumber,
        email: value.email ? candid_some(value.email) : candid_none(),
        creditLimit: value.creditLimit,
        address: value.address,
        notes: value.notes
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes: string;
    paymentType: PaymentType;
    customerId: CustomerId;
    amount: bigint;
}): {
    notes: string;
    paymentType: _PaymentType;
    customerId: _CustomerId;
    amount: bigint;
} {
    return {
        notes: value.notes,
        paymentType: to_candid_PaymentType_n31(_uploadFile, _downloadFile, value.paymentType),
        customerId: value.customerId,
        amount: value.amount
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loanDurationMonths?: bigint;
    dueDate?: Timestamp;
    description: string;
    totalDays?: bigint;
    dailyAmount?: number;
    interestRate?: number;
    notes: string;
    repaymentMode?: RepaymentMode;
    repaymentType?: RepaymentType;
    customerId: CustomerId;
    amount: bigint;
}): {
    loanDurationMonths: [] | [bigint];
    dueDate: [] | [_Timestamp];
    description: string;
    totalDays: [] | [bigint];
    dailyAmount: [] | [number];
    interestRate: [] | [number];
    notes: string;
    repaymentMode: [] | [_RepaymentMode];
    repaymentType: [] | [_RepaymentType];
    customerId: _CustomerId;
    amount: bigint;
} {
    return {
        loanDurationMonths: value.loanDurationMonths ? candid_some(value.loanDurationMonths) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        totalDays: value.totalDays ? candid_some(value.totalDays) : candid_none(),
        dailyAmount: value.dailyAmount ? candid_some(value.dailyAmount) : candid_none(),
        interestRate: value.interestRate ? candid_some(value.interestRate) : candid_none(),
        notes: value.notes,
        repaymentMode: value.repaymentMode ? candid_some(to_candid_RepaymentMode_n35(_uploadFile, _downloadFile, value.repaymentMode)) : candid_none(),
        repaymentType: value.repaymentType ? candid_some(to_candid_RepaymentType_n37(_uploadFile, _downloadFile, value.repaymentType)) : candid_none(),
        customerId: value.customerId,
        amount: value.amount
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes: string;
    paymentType: PaymentType;
    amount: bigint;
}): {
    notes: string;
    paymentType: _PaymentType;
    amount: bigint;
} {
    return {
        notes: value.notes,
        paymentType: to_candid_PaymentType_n31(_uploadFile, _downloadFile, value.paymentType),
        amount: value.amount
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loanDurationMonths?: bigint;
    dueDate?: Timestamp;
    description: string;
    totalDays?: bigint;
    dailyAmount?: number;
    interestRate?: number;
    notes: string;
    repaymentMode?: RepaymentMode;
    repaymentType?: RepaymentType;
    amount: bigint;
}): {
    loanDurationMonths: [] | [bigint];
    dueDate: [] | [_Timestamp];
    description: string;
    totalDays: [] | [bigint];
    dailyAmount: [] | [number];
    interestRate: [] | [number];
    notes: string;
    repaymentMode: [] | [_RepaymentMode];
    repaymentType: [] | [_RepaymentType];
    amount: bigint;
} {
    return {
        loanDurationMonths: value.loanDurationMonths ? candid_some(value.loanDurationMonths) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        totalDays: value.totalDays ? candid_some(value.totalDays) : candid_none(),
        dailyAmount: value.dailyAmount ? candid_some(value.dailyAmount) : candid_none(),
        interestRate: value.interestRate ? candid_some(value.interestRate) : candid_none(),
        notes: value.notes,
        repaymentMode: value.repaymentMode ? candid_some(to_candid_RepaymentMode_n35(_uploadFile, _downloadFile, value.repaymentMode)) : candid_none(),
        repaymentType: value.repaymentType ? candid_some(to_candid_RepaymentType_n37(_uploadFile, _downloadFile, value.repaymentType)) : candid_none(),
        amount: value.amount
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): {
    cash: null;
} | {
    deposit: null;
} | {
    online: null;
} {
    return value == PaymentType.cash ? {
        cash: null
    } : value == PaymentType.deposit ? {
        deposit: null
    } : value == PaymentType.online ? {
        online: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepaymentMode): {
    endOfTerm: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} | {
    halfYearly: null;
} | {
    daily: null;
} {
    return value == RepaymentMode.endOfTerm ? {
        endOfTerm: null
    } : value == RepaymentMode.quarterly ? {
        quarterly: null
    } : value == RepaymentMode.monthly ? {
        monthly: null
    } : value == RepaymentMode.halfYearly ? {
        halfYearly: null
    } : value == RepaymentMode.daily ? {
        daily: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepaymentType): {
    interestLoan: null;
} | {
    simple: null;
} | {
    fixedDaily: null;
} {
    return value == RepaymentType.interestLoan ? {
        interestLoan: null
    } : value == RepaymentType.simple ? {
        simple: null
    } : value == RepaymentType.fixedDaily ? {
        fixedDaily: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
